apiVersion: v1
kind: Secret
metadata:
  name: boutique-secrets
  namespace: boutique
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
  AUTH_DB_URL: postgresql://postgres:postgres123@boutique-postgres:5432/auth_db
  PRODUCTS_DB_URL: postgresql://postgres:postgres123@boutique-postgres:5432/products_db
  ORDERS_DB_URL: postgresql://postgres:postgres123@boutique-postgres:5432/orders_db
  USERS_DB_URL: postgresql://postgres:postgres123@boutique-postgres:5432/users_db
